spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: root
    password: test
    url: jdbc:mysql://localhost:3306/sunil_ecom

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8086

# Application Messages Goes Here
reports-service:
 messages:
  orderFetch: All Orders fetched successfully
  orderFetchErr: Failed to fetch all Orders
